name: Makefile CI

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Generate Geovision
      run: make gen_geovision && make gen_geovision_openapi

    - name: Update go dependencies
      run: go mod tidy
